-define(DB_HOSTNAME, "localhost").
-define(DB_USERNAME, "twoorl").
-define(DB_PASSWORD, "twoorl").
-define(DB_DATABASE, "twoorl").
-define(DB_POOL_SIZE, 50).
-define(APP_PATH, "/Users/dbravender/apps/twoorl/").
